server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 20
    connection-timeout: 20s
    accept-count: 100
    max-http-response-header-size: 8KB

spring:
  application:
    name: streaming-service
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

aws:
  s3:
    endpoint: http://localhost:4566
    bucket: videos
    region: us-east-1
    access-key: test
    secret-key: test

logging:
  level:
    com.streaming.integration: INFO