server:
  port: 8081

spring:
  application:
    name: streaming-service

aws:
  s3:
    endpoint: http://localstack:4566
    bucket: videos
    region: us-east-1
    access-key: test
    secret-key: test

kafka:
  bootstrap-servers: kafka:9092