server:
  port: 8081
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: streaming-service
  threads:
    virtual:
      enabled: true

aws:
  s3:
    endpoint: http://localhost:4566
    bucket: videos
    region: us-east-1
    access-key: test
    secret-key: test

kafka:
  bootstrap-servers: kafka:9092

logging:
  level:
    com.streaming.integration: INFO